# Generated by Django 3.1.14 on 2025-02-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20250208_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='text',
            new_name='description',
        ),
    ]
